=== RedoTV/third-course/web/lab6/marvel-schema-2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:simpleType name="nonEmptyString">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ratingType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0.0"/>
      <xs:maxInclusive value="10.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="actor">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="nonEmptyString"/>
        <xs:element name="age" type="xs:positiveInteger"/>
      </xs:sequence>
      <xs:attribute name="role" type="nonEmptyString" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="infoTypeWithAll">
    <xs:all>
      <xs:element name="name" type="nonEmptyString"/>
      <xs:element name="year" type="xs:gYear"/>
      <xs:element name="duration" type="xs:positiveInteger"/>
      
      <xs:element name="budget" type="xs:positiveInteger" minOccurs="0"/> 
    </xs:all>
  </xs:complexType>

  <xs:complexType name="movieTypeWithChoice">
    <xs:sequence>
      <xs:element name="info" type="infoTypeWithAll"/>
      <xs:choice>
        
        <xs:sequence>
          <xs:element ref="actor" maxOccurs="unbounded"/>
        </xs:sequence>
        
        <xs:element name="synopsis" type="xs:string"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="rating" type="ratingType" use="optional"/>
  </xs:complexType>

  <xs:element name="marvel-movies">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="movie" type="movieTypeWithChoice" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="founded" type="xs:gYear" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== RedoTV/third-course/web/lab6/marvel-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<marvel-movies 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="marvel-schema-2.xsd"
    founded="2008">

    <movie id="1" rating="8.0">
        <info>
            <year>2008</year>
            <budget>140000000</budget>
            <name>Железный человек</name>
            <duration>126</duration>
        </info>
        <actor role="Tony Stark">
            <name>Роберт Дауни мл.</name>
            <age>43</age>
        </actor>
        <actor role="Pepper Potts">
            <name>Гвинет Пэлтроу</name>
            <age>36</age>
        </actor>
    </movie>
    
    <movie id="2">
        <info>
            <name>Халк</name>
            <year>2008</year>
            <duration>112</duration>
        </info>
        <synopsis>Ученый Брюс Бэннер подвергается воздействию гамма-лучей и превращается в зеленого монстра, когда злится.</synopsis>
    </movie>

    <movie id="4" rating="7.0">
        <info>
            <name>Тор</name>
            <year>2011</year>
            <duration>115</duration>
            <budget>150000000</budget>
        </info>
        <actor role="Thor">
            <name>Крис Хемсворт</name>
            <age>28</age>
        </actor>
    </movie>
    
</marvel-movies>
