<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE marvel-movies [
<!ENTITY company "Marvel Studios">
<!ENTITY copyright "© 2025">

<!ELEMENT marvel-movies (movie+)>
<!ATTLIST marvel-movies
  version CDATA #FIXED "1.0"
>

<!ELEMENT movie (info, actor+, production_info)>
<!ATTLIST movie
  id ID #REQUIRED
  rating (G | PG | PG-13 | R) "PG-13"
  status (Released | In-Production) #REQUIRED
>
<!ELEMENT info (name, year, duration, budget)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT budget (#PCDATA)>

<!ELEMENT actor (name, age)>
<!ATTLIST actor
  role CDATA #REQUIRED
>
<!ELEMENT age (#PCDATA)>

<!ELEMENT production_info (producer, copyright_notice)>
<!ELEMENT producer (#PCDATA)>
<!ELEMENT copyright_notice (#PCDATA)>
]>
<marvel-movies version="1.0">
    <movie id="m1" status="Released">
        <info>
            <name>Железный человек</name>
            <year>2008</year>
            <duration>126</duration>
            <budget>140000000</budget>
        </info>
        <actor role="Tony Stark">
            <name>Роберт Дауни мл.</name>
            <age>43</age>
        </actor>
        <actor role="Pepper Potts">
            <name>Гвинет Пэлтроу</name>
            <age>36</age>
        </actor>
        <actor role="James Rhodes">
            <name>Терренс Ховард</name>
            <age>39</age>
        </actor>
        <production_info>
            <producer>&company;</producer>
            <copyright_notice>&copyright;</copyright_notice>
        </production_info>
    </movie>
    <movie id="m2" status="Released">
        <info>
            <name>Халк</name>
            <year>2008</year>
            <duration>112</duration>
            <budget>150000000</budget>
        </info>
        <actor role="Bruce Banner">
            <name>Эдвард Нортон</name>
            <age>39</age>
        </actor>
        <actor role="Betty Ross">
            <name>Лив Тайлер</name>
            <age>31</age>
        </actor>
        <production_info>
            <producer>&company;</producer>
            <copyright_notice>&copyright;</copyright_notice>
        </production_info>
    </movie>
    <movie id="m3" status="Released">
        <info>
            <name>Железный человек 2</name>
            <year>2010</year>
            <duration>124</duration>
            <budget>200000000</budget>
        </info>
        <actor role="Tony Stark">
            <name>Роберт Дауни мл.</name>
            <age>45</age>
        </actor>
        <actor role="Natasha Romanoff">
            <name>Скарлетт Йоханссон</name>
            <age>26</age>
        </actor>
        <actor role="Ivan Vanko">
            <name>Микки Рурк</name>
            <age>58</age>
        </actor>
        <production_info>
            <producer>&company;</producer>
            <copyright_notice>&copyright;</copyright_notice>
        </production_info>
    </movie>
    <movie id="m4" status="Released">
        <info>
            <name>Тор</name>
            <year>2011</year>
            <duration>115</duration>
            <budget>150000000</budget>
        </info>
        <actor role="Thor">
            <name>Крис Хемсворт</name>
            <age>28</age>
        </actor>
        <actor role="Jane Foster">
            <name>Натали Портман</name>
            <age>30</age>
        </actor>
        <actor role="Loki">
            <name>Том Хиддлстон</name>
            <age>30</age>
        </actor>
        <production_info>
            <producer>&company;</producer>
            <copyright_notice>&copyright;</copyright_notice>
        </production_info>
    </movie>
    <movie id="m5" status="Released">
        <info>
            <name>Первый мститель</name>
            <year>2011</year>
            <duration>124</duration>
            <budget>140000000</budget>
        </info>
        <actor role="Steve Rogers">
            <name>Крис Эванс</name>
            <age>30</age>
        </actor>
        <actor role="Peggy Carter">
            <name>Хейли Этвелл</name>
            <age>29</age>
        </actor>
        <production_info>
            <producer>&company;</producer>
            <copyright_notice>&copyright;</copyright_notice>
        </production_info>
    </movie>
    <movie id="m6" status="Released">
        <info>
            <name>Мстители</name>
            <year>2012</year>
            <duration>143</duration>
            <budget>220000000</budget>
        </info>
        <actor role="Tony Stark">
            <name>Роберт Дауни мл.</name>
            <age>47</age>
        </actor>
        <actor role="Steve Rogers">
            <name>Крис Эванс</name>
            <age>31</age>
        </actor>
        <actor role="Thor">
            <name>Крис Хемсворт</name>
            <age>29</age>
        </actor>
        <actor role="Bruce Banner">
            <name>Марк Руффало</name>
            <age>45</age>
        </actor>
        <actor role="Natasha Romanoff">
            <name>Скарлетт Йоханссон</name>
            <age>28</age>
        </actor>
        <actor role="Clint Barton">
            <name>Джереми Реннер</name>
            <age>41</age>
        </actor>
        <production_info>
            <producer>&company;</producer>
            <copyright_notice>&copyright;</copyright_notice>
        </production_info>
    </movie>
</marvel-movies>